import './styles/globals.css'
import 'antd/dist/reset.css'
import { Inter, Roboto } from 'next/font/google'
import { Providers } from './providers'
import Header from './components/header/header'
import Footer from './components/footer/footer'

const inter = Inter({ subsets: ['latin'] })
const roboto = Roboto({ subsets: ['latin'], weight: '400' })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  // <meta name="viewport" content="width=device-width, initial-scale=1">
  viewport: 'width=device-width, initial-scale=1 ,maximum-scale=1',
}

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={roboto.className}>
        <Providers>
          <Header />
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  )
}
